classdef dendParamConfig
    properties (Constant)
        dendParamsBerry = DendriteParams(nSynapses=2000, branchSize=20, ...
            synStrength=10, synAttenuation=10, ...
            branchThresh=15, branchStrength=7, somaThresh=20, backpropAP=7, ...
            synNoise=0.2, branchNoise=0.2, somaNoise=0, weightsRange=1, ...
            duPotent=3, duDepress=-0.3, duDecay=-0.3, duBaseline=0, ...
            uRecycle=-3, uMax=10, plastTime=4, ...
            scaleNMDA=-0.1, scaleNoNMDA=0.003, branchGLeak=1, ...
            initSynGInhib=4, somaPlus=0.1, somaMinus=-0.005, somaGLeak=0.1, initSomaGInhib=0.5);
        
        dendParamsOpt = DendriteParams(nSynapses=2000, branchSize=20, ...
            synStrength=10, synAttenuation=10, ...
            branchThresh=15, branchStrength=7, somaThresh=20, backpropAP=7, ...
            synNoise=0.2, branchNoise=0.2, somaNoise=0, weightsRange=1, ...
            duPotent=3, duDepress=-0.3, duDecay=-0.3, duBaseline=0.01, ...
            uRecycle=-3, uMax=10, plastTime=4, ...
            scaleNMDA=-0.1, scaleNoNMDA=0.003, branchGLeak=1, ...
            initSynGInhib=4, somaPlus=0.1, somaMinus=-0.005, somaGLeak=0.1, initSomaGInhib=0.5);

        dendParamsGridSearch = DendriteParams(nSynapses=2000, branchSize=20, ...
            synStrength=10, synAttenuation=10, ...
            branchThresh=15, branchStrength=7, somaThresh=20, backpropAP=7, ...
            synNoise=0.2, branchNoise=0.2, somaNoise=0, weightsRange=1, ...
            duPotent=3, duDepress=-0.3, duDecay=-0.3, duBaseline=0.01, ...
            uRecycle=-3, uMax=10, plastTime=4, ...
            scaleNMDA=-12, scaleNoNMDA=0.003, branchGLeak=1, ...
            initSynGInhib=4, somaPlus=0.1, somaMinus=-0.005, somaGLeak=0.1, initSomaGInhib=0.5);
    end
end